update

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -25,4 +25,4 @@ jobs:
           npm install && npm install -g @lhci/cli@0.6.x
           npm run build
       - name: run Lighthouse CI
-        run: lhci autorun --upload.target=temporary-public-storage --staticDistDir=./build || echo "LHCI failed!"
+        run: lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
